


RFC9- FUNCIONA

Select us.nombre, us.identificacion, count(*)
from usuario us
inner join reserva res
on us.identificacion=res.id_usuario
inner join apartan ap
on res.id=ap.idreserva
inner join
habitacion hab
on ap.numerohabitacion=hab.numerohabitacion
inner join sirven sirv
on hab.numerohabitacion=sirv.numerohabitacion
where sirv.FECHAUSO between 2019010101 and 2019070101
and sirv.IDSERVICIO=1
group by us.identificacion, us.nombre;


RFC10-Terminado

select *
from usuario
where identificacion not in(
Select us.identificacion
from usuario us
inner join reserva res
on us.identificacion=res.id_usuario
inner join apartan ap
on res.id=ap.idreserva
inner join
habitacion hab
on ap.numerohabitacion=hab.numerohabitacion
inner join sirven sirv
on hab.numerohabitacion=sirv.numerohabitacion
where sirv.FECHAUSO between 2019010101 and 2019070101
and sirv.IDSERVICIO=1);



RFC12-FUNCIONA
SELECT US.IDENTIFICACION
FROM USUARIO US
INNER JOIN RESERVA RES
ON US.IDENTIFICACION=RES.ID_USUARIO
INNER JOIN APARTAN AP
ON RES.ID=AP.IDRESERVA
INNER JOIN HABITACION HAB
ON AP.NUMEROHABITACION=HAB.NUMEROHABITACION
INNER JOIN SIRVEN SIRV
ON HAB.NUMEROHABITACION=SIRV.NUMEROHABITACION
INNER JOIN SERVICIOS SERV
ON SIRV.IDSERVICIO=SERV.ID
WHERE SERV.COSTO>=20
OR SERV.NOMBRE LIKE'%SPA%'
OR SERV.NOMBRE LIKE '%SALA REUNIONES%'
OR SERV.NOMBRE LIKE '%SALA CONFERENCIAS%';




select usuario.identificacion, count(reserva.id)
from usuario
inner join reserva
on usuario.identificacion=reserva.id_usuario
where reserva.fechainicio between 20180101 and 20180401
or reserva.fechainicio between 20180401 and 20180701
or reserva.fechainicio between 20180701 and 20180901
or reserva.fechainicio between 20180901 and 20190101
group by usuario.identificacion
order by count(reserva.id) desc;



//REQUERIMIENTO DE CONSULTA 11
//PARA TODAS LAS SEMANAS DEL AÑO (DE SÀBADO A SÀBADO) ENCONTRAR LOS SERVICIOS MÀS Y MENOS
//SOLICITADAS, Y LAS HABITACIONES MÀS Y MENOS SOLICITADAS





//SERVICIOS UTILIZADOS POR USUARIO
SELECT RESP.NOMBRE, SUM(RESP.NUMEROVECES) AS TOTALVECES
FROM(
        SELECT COUNT(SER.ID) AS NUMEROVECES, SER.NOMBRE,  SIR.FECHAUSO
        FROM SERVICIOS SER, SIRVEN SIR
        WHERE SER.ID = SIR.IDSERVICIO AND SIR.FECHAUSO BETWEEN '2019010100' AND '2019010823'
        GROUP BY SIR.FECHAUSO, SER.NOMBRE
    )RESP
GROUP BY RESP.NOMBRE
ORDER BY TOTALVECES DESC






//SERVICIOS UTILIZADOS POR CONVENCION
SELECT SER.ID, SER.NOMBRE, COUNT(RESC.ID) AS NUMEROVECES
FROM SERVICIOS SER, SERVICIOS_CONVENCION SERC, RESERVA_CONVENCIONES RESC
WHERE SER.ID = SERC.ID_RESERVA AND SERC.ID_RESERVA = RESC.ID
 AND ((RESC.FECHAINICIO BETWEEN '20190301' AND '20190820') OR (RESC.FECHAFIN BETWEEN '20190301' AND '20190820'))
GROUP BY SER.ID, SER.NOMBRE
ORDER BY NUMEROVECES DESC


//SERVICIOS EN CONJUNTO EN FECHA DADA
SELECT TOT.ID, TOT.NOMBRE, SUM(NUMVECES) AS TOTALVECES
FROM (
        SELECT RESP.ID, RESP.NOMBRE, SUM(RESP.NUMEROVECES) AS NUMVECES
        FROM(
                SELECT SER.ID, COUNT(SER.ID) AS NUMEROVECES, SER.NOMBRE,  SIR.FECHAUSO
                FROM SERVICIOS SER, SIRVEN SIR
                WHERE SER.ID = SIR.IDSERVICIO AND SIR.FECHAUSO BETWEEN '2019010100' AND '2019010823'
                GROUP BY SIR.FECHAUSO, SER.NOMBRE, SER.ID
            )RESP
        GROUP BY RESP.ID, RESP.NOMBRE

        UNION ALL

        SELECT SER.ID, SER.NOMBRE, COUNT(RESC.ID) AS NUMEROVECES
        FROM SERVICIOS SER, SERVICIOS_CONVENCION SERC, RESERVA_CONVENCIONES RESC
        WHERE SER.ID = SERC.ID_RESERVA AND SERC.ID_RESERVA = RESC.ID
         AND ((RESC.FECHAINICIO BETWEEN '20190301' AND '20190820') OR (RESC.FECHAFIN BETWEEN '20190301' AND '20190820'))
        GROUP BY SER.ID, SER.NOMBRE
    )TOT
GROUP BY TOT.ID, TOT.NOMBRE
ORDER BY TOTALVECES DESC








//HABITACIONES
SELECT RESP.NUMEROHABITACION, COUNT(ID) AS NUMEROVECES
FROM(
        SELECT AP.NUMEROHABITACION, RES.ID, RES.FECHAINICIO, RES.FECHAFIN
        FROM APARTAN AP, RESERVA RES
        WHERE AP.IDRESERVA = RES.ID
            AND ((RES.FECHAINICIO BETWEEN '20181010' AND '20181020') OR (RES.FECHAFIN BETWEEN '20181010' AND '20181020'))

        UNION ALL

        SELECT HABC.NUMEROHABITACION, RESC.ID, RESC.FECHAINICIO, RESC.FECHAFIN
        FROM HABITACION_CONVENCION HABC, RESERVA_CONVENCIONES RESC
        WHERE HABC.ID_RESERVA = RESC.ID
             AND ((RESC.FECHAINICIO BETWEEN '20181010' AND '20181020') OR (RESC.FECHAFIN BETWEEN '20181010' AND '20181020'))
    ) RESP
GROUP BY RESP.NUMEROHABITACION
ORDER BY NUMEROVECES DESC
