SELECT NUMEROHABITACION ,SUM(COSTO)
FROM HABITACION hab
INNER JOIN APARTAN ap
ON hab.NUMEROHABITACION=ap.NUMEROHABITACION
INNER JOIN RESERVA res
ON ap.IDRESERVA=res.ID
GROUP BY NUMEROHABITACION;